name: implicitly_animated_list
description: A Flutter widget that implicitly animates a list whenever it rebuilds with new items.
version: 1.0.0
author: Marcel Garus
homepage: https://github.com/marcelgarus/implicitly_animated_list

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  list_diff: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
